### ISSUE TITLE
comparaison check (equals)

### ISSUE THREAD

**Issue by mohamine18** [cherifGsoul/php-algerian-mobile-phone-number#6]
$phoneNumber = AlgerianMobilePhoneNumber::fromString('0699000000');
$other = AlgerianMobilePhoneNumber::fromString('0699000000');
$phoneNumber->equals($other); // -> true

what if
$phoneNumber = AlgerianMobilePhoneNumber::fromString('0699000000');
$other = AlgerianMobilePhoneNumber::fromString('00213699000000');
$phoneNumber->equals($other); // -> ???

**Comment by cherifGsoul** [comment]
@mohamine18 Yes this make sense and should be fixed, it will be great if you can open PR.

**Comment by cherifGsoul** [comment]
I think the best way to handle this is to omit the indicative part (0, +213 or 00213) and just keep the phone number starting from 5, 6 or 7 part.
